name: Update Deps

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  execute-action-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir informações do Push
        run: |
          echo "OK"
