env:
  GO_VERSION: 1.21.4

name: Update Dependencies
on:
  workflow_dispatch:
    inputs:
      commit:
        required: true
        type: string
        
jobs:
  dep_update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v4
      - run: git log
      - run: git checkout -b branch_to_merge dev
      - run: git log

      - name: Update minor and patch-level dependencies
        run: go get -t -u ./...

      - name: Tidy
        run: go mod tidy

      - name: Commit
        run: git status
      - run: git add .
      - run: git config --global user.name "BrunoGambim"
      - run: git commit -m "update deps"
      - run: git status

        
      - name: create pull request
        run: gh pr create -B dev -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
