env:
  GO_VERSION: 1.21.4

name: Update and Push Jarbas Commons
on:
  workflow_dispatch:
    inputs:
      commit:
        required: true
        type: string
        
jobs:
  dep_update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.TOKEN}}

      - name: Update Jarbas-Commons
        run: go get github.com/BrunoGambim/TesteGAA@${{ inputs.commit }}

      - name: Tidy
        run: go mod tidy

      - name: Commit
        run: git add .
      - run: git config --global user.name "${{ github.event.sender.login }}"
      - run: git config --global user.email "${{ github.event.sender.id }}+${{ github.event.sender.login }}@users.noreply.github.com"
      - run: git commit -m "update jarbas-commons to ${{ inputs.commit }}"
      - run: git push origin bump/update-jarbas-commons
